# Generated by Django 4.1.4 on 2022-12-29 08:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tkp_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id_tkp', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Организация (Клиент)')),
                ('data_create_tkp', models.DateField(default=datetime.date.today, verbose_name='Дата ТКП')),
                ('time_update_tkp', models.DateTimeField(auto_now=True)),
                ('summa_tkp', models.PositiveSmallIntegerField(default=0, help_text='указывать сумму в рублях с НДС', verbose_name='Сумма ТКП')),
                ('kontakt_tkp', models.CharField(max_length=200, verbose_name='Контактное лицо')),
                ('city_client', models.CharField(max_length=200, verbose_name='Населённый пункт')),
                ('description_tkp', models.CharField(max_length=200, verbose_name='Оборудование, содержание/предложение')),
                ('tender_tkp', models.BooleanField(default=False, verbose_name='Тендер, да/нет')),
                ('notes_tkp', models.CharField(max_length=200, verbose_name='Примечание')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='URL')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
