# Generated by Django 4.1.4 on 2022-12-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tkp_new',
            name='notes_tkp',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Примечание'),
        ),
    ]
