# Generated by Django 4.1.4 on 2022-12-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_tkp_new_notes_tkp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tkp_new',
            name='tender_tkp',
            field=models.BooleanField(default=False, verbose_name='Тендер'),
        ),
    ]
