# Generated by Django 4.1.4 on 2022-12-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_tkp_new_tender_tkp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tkp_new',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True, verbose_name='URL'),
        ),
    ]
