# Generated by Django 4.1.4 on 2022-12-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_tkp_new_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tkp_new',
            name='slug',
        ),
    ]
